# ===================================
# PROD Profile Configuration
# ===================================
spring.h2.console.enabled=false
spring.jpa.show-sql=false
logging.level.com.ecommerce=WARN
logging.level.org.springframework=ERROR
